site_name: 浩哈哈哈哈
site_url: https://chat.haohaha.cn
theme: 
  name: material
  icon:
    logo: material/noodles
  favicon: https://chat.haohaha.cn/image/favicon.png
  palette:
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: deep orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式

  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - navigation.prune # 折叠
    - search.suggest
    - search.highlight
    # Instant Loading
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # Anchor tracking
    - navigation.tracking
    
  language: zh

nav:
  - Home: http://haohaha.cn
  - Be_Rational: http://cs.haohaha.cn
  - Chat_Polka:  
    - Home: index.md
    - 年度总结: 
      - 2024年度总结: 3-Annual/2024.md
      - 2022-2023年度总结: 3-Annual/2022-2023.md
      - 2021年度总结: 3-Annual/2021.md
      - 2023年个人财报: 3-Annual/2023-personal_financial_report.md
    - 周记: 
      - 2025周记:
        - 1-Weekly/2025/index.md
        - 0824-0830 第26周: 1-Weekly/2025/0824-0830-26th.md
        - 0810-0823 第24&25周: 1-Weekly/2025/0810-0823-24&25th.md
        - 0803-0809 第23周: 1-Weekly/2025/0803-0809-23rd.md
        - 0727-0802 第22周: 1-Weekly/2025/0727-0802-22nd.md
        - 0720-0726 第21周: 1-Weekly/2025/0720-0726-21st.md
        - 0713-0719 第20周: 1-Weekly/2025/0713-0719-20th.md
        - 0629-0712 第18-19周: 1-Weekly/2025/0629-0712-18&19th.md
        - 0622-0628 第17周: 1-Weekly/2025/0622-0628-17th.md
        - 0615-0621 第16周: 1-Weekly/2025/0615-0621-16th.md
        - 0608-0614 第15周: 1-Weekly/2025/0608-0614-15th.md
        - 0525-0607 第13-14周: 1-Weekly/2025/0525-0607-13&14th.md
        - 0518-0524 第12周: 1-Weekly/2025/0518-0524-12th.md
        - 0511-0517 第11周: 1-Weekly/2025/0511-0517-11th.md
        - 0504-0510 第10周: 1-Weekly/2025/0504-0510-10th.md
        - 0427-0503 第9周: 1-Weekly/2025/0427-0503-9th.md
        - 0420-0426 第8周: 1-Weekly/2025/0420-0426-8th.md
        - 0413-0419 第7周: 1-Weekly/2025/0413-0419-7th.md
        - 0406-0412 第6周: 1-Weekly/2025/0406-0412-6th.md
        - 0330-0405 第5周: 1-Weekly/2025/0330-0405-5th.md
        - 0323-0329 第4周: 1-Weekly/2025/0323-0329-4th.md
        - 0316-0322 第3周: 1-Weekly/2025/0316-0322-3rd.md
        - 0309-0315 第2周: 1-Weekly/2025/0309-0315-2nd.md
        - 0302-0308 第1周: 1-Weekly/2025/0302-0308-1st.md
      - 2021-2022周记: 
        - 总览: 1-Weekly/2021-2022/0_Week_summary_by_Zhang-Hanzhe.md
        - 第1周: 1-Weekly/2021-2022/1st_week_by_Zhang-Hanzhe.md
        - 第2周: 1-Weekly/2021-2022/2nd_week_by_Zhang-Hanzhe.md
        - 第3周: 1-Weekly/2021-2022/3rd_week_by_Zhang-Hanzhe.md
        - 第4周: 1-Weekly/2021-2022/4th_week_by_Zhang-Hanzhe.md
        - 第5周: 1-Weekly/2021-2022/5th_week_by_Zhang-Hanzhe.md
        - 第6周: 1-Weekly/2021-2022/6th_week_by_Zhang-Hanzhe.md
        - 第7周: 1-Weekly/2021-2022/7th_week_by_Zhang-Hanzhe.md
        - 第8-9周: 1-Weekly/2021-2022/8&9th_week_by_Zhang-Hanzhe.md
        - 第10-13周: 1-Weekly/2021-2022/10-13th_week_by_Zhang-Hanzhe.md
        - 第14-19周: 1-Weekly/2021-2022/14-19th_week_by_Zhang-Hanzhe.md
        - 第20-22周: 1-Weekly/2021-2022/20-22th_week_by_Zhang-Hanzhe.md
        - 第23周: 1-Weekly/2021-2022/23th_week_by_Zhang-Hanzhe.md
        - 第24周: 1-Weekly/2021-2022/24th_week_by_Zhang-Hanzhe.md
        - 第25周: 1-Weekly/2021-2022/25th_week_by_Zhang-Hanzhe.md
        - 第26-27周: 1-Weekly/2021-2022/26&27th_week_by_Zhang-Hanzhe.md
        - 第28-30周: 1-Weekly/2021-2022/28-30th_week_by_Zhang-Hanzhe.md
        - 第31-33周: 1-Weekly/2021-2022/31-33th_week_by_Zhang-Hanzhe.md
        - 第34周: 1-Weekly/2021-2022/34th_week_by_Zhang-Hanzhe.md
        - 第35-39周: 1-Weekly/2021-2022/35-39th_week_by_Zhang-Hanzhe.md
        - 第40周: 1-Weekly/2021-2022/40th_week_by_Zhang-Hanzhe.md
        - 第41周: 1-Weekly/2021-2022/41th_week_by_Zhang-Hanzhe.md
        - 第42周: 1-Weekly/2021-2022/42th_week_by_Zhang-Hanzhe.md
        - 第43周: 1-Weekly/2021-2022/43th_week_by_Zhang-Hanzhe.md
        - 第44-47周: 1-Weekly/2021-2022/44-47th_week_Summary_by_Zhang-Hanzhe.md
        - 第48-49周: 1-Weekly/2021-2022/48-49th_week_by_Zhang-Hanzhe.md
        - 第50周: 1-Weekly/2021-2022/50th_week_by_Zhang-Hanzhe.md
        - 第51-52周: 1-Weekly/2021-2022/51-52th_week_by_Zhang-Hanzhe.md
        - 第53-57周: 1-Weekly/2021-2022/53-57th_week_by_Zhang-Hanzhe.md
    - 哲·理·集:
      - 8-Philoreason/index.md
      - 随笔 夕阳无限好 黄昏也亦然: 8-Philoreason/001.md
      - 诗 壮哉，士也！: 8-Philoreason/002.md
      - 议论 无志青年: 8-Philoreason/003.md
      - 随笔 无题-鸟鸣: 8-Philoreason/004.md
      - 小说 哥儿仨: 8-Philoreason/005.md
      - 诗 骄兵必败，哀兵必胜: 8-Philoreason/006.md
      - 诗 己亥七月二十归唐而作: 8-Philoreason/007.md
      - 随笔 风: 8-Philoreason/008.md
      - 小说 守夜: 8-Philoreason/009.md
      - 议论 优优劣劣: 8-Philoreason/010.md
      - 词 卜算子·地震: 8-Philoreason/011.md
    - 读书笔记: 
      - 9-read/index.md
      - 大道-段永平投资问答录: 9-read/001.md
    - 月度记录:
      - 2024年02月: 2-Monthly/2024-02.md
      - 2024年01月: 2-Monthly/2024-01.md
    - 日记: 
      - 2024年11月08日-杂谈: 0-Diary/2024-11-08.md
      - 2024年04月16日-碎碎念: 0-Diary/2024-04-16.md
      - 2022-2023每日学习记录: 0-Diary/2022-2023.md
    - 所思所想所感:
      - 抄录_送东阳马生序: 4-thought/Farewell_Ma/Xv.md
      - La vaguelette 轻涟: 4-thought/la-vaguelette/l-v.md 
      - 服务器-云端工作随想: 4-thought/Server-Build/think.md
      - 个人学习工作流: 4-thought/Personnal_Learning/flow.md
      - MarginNote 4 英语精读全流程: 4-thought/Personnal_Learning/Eng-mn4.md
    - 美食:
      - 菜谱: 5-delicious/menu.md
      - 品尝: 5-delicious/taste.md
      - 制作: 5-delicious/cook.md
    - 美景:
      - 所见: 6-scenery/scenery.md
    - 生活:
      - 选房小经验: 7-Life/rent-house/exercise.md
      - 家具列表: 7-Life/furniture/wanna.md
      - 交通考察报告: 7-Life/rent-house/Traffic-Survey.md
      - 冰箱备料/管理/制作办法: 7-Life/cook/method.md
      - Hzone: 7-Life/Hzone/dream.md
    - 唐山游玩:
      - 唐山旅游景点: Tangshan-Reception/Tangshan-tourist-attractions.md
    - 测试文档: format-example/format-example.md
  - Algorithm: http://alg.haohaha.cn

plugins:
  - mermaid2:
      arguments:
        theme: light
# - rss:
#     match_path: blog/posts/.*
#     date_from_meta:
#       as_creation: date
#     categories:
#       - categories
# - blog:
#     authors_profiles: true

markdown_extensions:
  # attr_list
  - markdown.extensions.attr_list
  # List
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Icons, Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Formatting: Highlight, Sub & Keyboard Keys.
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
# - 'mkdocs/css/extensions.css' # 图片放大支持
# - 'mkdocs/css/simpleLightbox.min.css' # 图片放大支持
  
# extra_javascript:
# - 'https://code.jquery.com/jquery-3.2.1.min.js' # 图片放大支持
# - 'mkdocs/js/simpleLightbox.min.js' # 图片放大支持
# - 'mkdocs/js/extensions.js' # 图片放大支持
  
extra:
  homepage: http://haohaha.cn
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
    - icon: simple/githubactions
      link: https://github.com/Haohahahaha/chat/actions
      name: GitHub Actions

## [bottom-left corner]
copyright: 
  <a href="https://beian.miit.gov.cn/" target="_blank">冀ICP备2024078994号</a><br/>
  <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=13020302001386" target="_blank">冀公网安备13020302001386号</a><br/>
  Copyright &copy; 2022-现在 浩哈哈哈哈_ # 左下角的版权声明