site_name: 浩哈哈哈哈
site_url: https://chat.haohaha.cn
theme: 
  name: material
  icon:
    logo: material/noodles
  favicon: https://chat.haohaha.cn/image/favicon.png
  palette:
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: deep orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式

  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.prune
    - search.suggest
    - search.highlight
    # Instant Loading
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # Anchor tracking
    - navigation.tracking
    
  language: zh

nav:
  - 主页: http://haohaha.cn
  - CS笔记: http://cs.haohaha.cn
  - 闲聊波尔卡:  
    - Home: index.md
#   - Blog:
#     - blog/index.md
    - 不成熟的所思所想所感:
      - La vaguelette 轻涟: thought/la-vaguelette/l-v.md 
      - 2022-2023年度总结: thought/2022-2023_summary/summary.md
    - 美食:
      - 品尝: delicious/taste.md
      - 制作: delicious/cook.md
    - 美景:
      - 所见: scenery/scenery.md
    - 测试文档:
      - format-example/format-example.md
  - OS学习: http://os.haohaha.cn
  - 算法打卡: http://alg.haohaha.cn
  - 数学笔记: http://math.haohaha.cn
  - 英语笔记: http://eng.haohaha.cn

plugins:
  - mermaid2:
      arguments:
        theme: light
# - rss:
#     match_path: blog/posts/.*
#     date_from_meta:
#       as_creation: date
#     categories:
#       - categories
# - blog:
#     authors_profiles: true

markdown_extensions:
  # attr_list
  - markdown.extensions.attr_list
  # List
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Icons, Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Formatting: Highlight, Sub & Keyboard Keys.
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
# - 'mkdocs/css/extensions.css' # 图片放大支持
# - 'mkdocs/css/simpleLightbox.min.css' # 图片放大支持
  
# extra_javascript:
# - 'https://code.jquery.com/jquery-3.2.1.min.js' # 图片放大支持
# - 'mkdocs/js/simpleLightbox.min.js' # 图片放大支持
# - 'mkdocs/js/extensions.js' # 图片放大支持
  
extra:
  homepage: http://haohaha.cn
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
    - icon: simple/githubactions
      link: https://github.com/Haohahahaha/chat/actions
      name: GitHub Actions

## [bottom-left corner]
copyright: Copyright &copy; 2022-现在 浩哈哈哈哈_ # 左下角的版权声明
