site_name: 浩哈哈哈哈
theme: 
  name: material
  icon:
    logo: material/library
  palette:
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: deep orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式

  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
  language: zh

nav:
  - 主页: http://haohaha.cn
  - 算法打卡: http://alg.haohaha.cn
  - 数学笔记: http://math.haohaha.cn
  - 英语笔记: http://eng.haohaha.cn
  - CS笔记: http://cs.haohaha.cn
  - 我爱OS: http://os.haohaha.cn
  - 闲聊波尔卡:  
    - Home: index.md
    - Plan: 
      - 极限规划: plan/PEE-plans.md
      - 周任务: plan/Week-Plan.md
      - todo-list: plan/todo-list.md
    - report:
      - 230903: OSCA/report/230903.md
    - 不成熟的所思所想所感:
      - La vaguelette 轻涟: thought/la-vaguelette/l-v.md
    - 建设清单: construction/construction.md
    - 美食:
      - 品尝: delicious/taste.md
      - 制作: delicious/cook.md
    - 美景:
      - 所见: scenery/scenery.md
    - 测试文档:
      - test/test.md

plugins:
  - mermaid2:
      arguments:
        theme: light

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
extra:
  homepage: http://haohaha.cn
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
## [bottom-left corner]
copyright: Copyright &copy; 2022-现在 浩哈哈哈哈_ # 左下角的版权声明
